export declare enum Languages {
    English = "en",
    Arabic = "ar",
    Azerbaijani = "az",
    Chinese = "zh",
    Czech = "gs",
    Danish = "da",
    Dutch = "nl",
    Esperanto = "eo",
    Finnish = "fi",
    French = "fr",
    German = "de",
    Greek = "el",
    Hebrew = "he",
    Hindi = "hi",
    Hungarian = "hu",
    Indonesian = "id",
    Irish = "ga",
    Italian = "it",
    Japanese = "jp",
    Korean = "ko",
    Persian = "fa",
    Polish = "pl",
    Portuguese = "pt",
    Russian = "ru",
    Slovak = "sk",
    Spanish = "es",
    Swedish = "sv",
    Turkish = "tr",
    Ukrainian = "uk"
}
export declare function translateText(text: string, source: Languages, target: Languages): Promise<string>;
